// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwGMeQ1FaMoVTD5zEXaNIismx1egofzQ',
    appId: '1:187636377240:web:d06013c4d511926d2dd2ed',
    messagingSenderId: '187636377240',
    projectId: 'movie-project-ebd1a',
    authDomain: 'movie-project-ebd1a.firebaseapp.com',
    storageBucket: 'movie-project-ebd1a.firebasestorage.app',
    measurementId: 'G-DD5L0DD95S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQe4qGqe0UXBJ2P6nawhYkMoJKTwP-0Mk',
    appId: '1:187636377240:android:89e163c7fff38dcb2dd2ed',
    messagingSenderId: '187636377240',
    projectId: 'movie-project-ebd1a',
    storageBucket: 'movie-project-ebd1a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTMFpLVD8T4-0J1s_9OiN7msuGCwHL3LY',
    appId: '1:187636377240:ios:35db6a157de0ac442dd2ed',
    messagingSenderId: '187636377240',
    projectId: 'movie-project-ebd1a',
    storageBucket: 'movie-project-ebd1a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTMFpLVD8T4-0J1s_9OiN7msuGCwHL3LY',
    appId: '1:187636377240:ios:35db6a157de0ac442dd2ed',
    messagingSenderId: '187636377240',
    projectId: 'movie-project-ebd1a',
    storageBucket: 'movie-project-ebd1a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwGMeQ1FaMoVTD5zEXaNIismx1egofzQ',
    appId: '1:187636377240:web:d1711d37cda60dec2dd2ed',
    messagingSenderId: '187636377240',
    projectId: 'movie-project-ebd1a',
    authDomain: 'movie-project-ebd1a.firebaseapp.com',
    storageBucket: 'movie-project-ebd1a.firebasestorage.app',
    measurementId: 'G-V8SD1PG412',
  );
}
